<a href="https://colab.research.google.com/github/div-yash/google-colab-projects/blob/main/GoogleColabBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

System Specifications

In [ ]:
!cat /proc/cpuinfo


processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.156
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4400.31
clflush size	: 64
cache_alignment	: 64
addres

In [ ]:
!cat /proc/meminfo

MemTotal:       13290480 kB
MemFree:         8776184 kB
MemAvailable:   12378908 kB
Buffers:          332364 kB
Cached:          3455992 kB
SwapCached:            0 kB
Active:           593556 kB
Inactive:        3664584 kB
Active(anon):       1120 kB
Inactive(anon):   470084 kB
Active(file):     592436 kB
Inactive(file):  3194500 kB
Unevictable:           4 kB
Mlocked:               4 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               404 kB
Writeback:             0 kB
AnonPages:        469836 kB
Mapped:           269416 kB
Shmem:              1416 kB
KReclaimable:     113452 kB
Slab:             149128 kB
SReclaimable:     113452 kB
SUnreclaim:        35676 kB
KernelStack:        4336 kB
PageTables:         9096 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645240 kB
Committed_AS:    1973880 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       10560 kB
VmallocChunk:    

Installing Libraries : pandas

In [ ]:
!pip install  pandas

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [ ]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [ ]:
print("Hello World")

Hello World


In [ ]:
print(3+5)

8


In [ ]:
!ls


Object_Technology_Lab_IT.doc  sample_data


# New section

**NumPy** : Numerical Python

Advantages:
1. allows several math operations
2. faster operations



In [ ]:
import numpy as np


List vs Numpy  - time taken

In [ ]:
from time import process_time


time taken by a list:


In [ ]:
python_list =[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time= process_time()

print(end_time-start_time)


0.0018118400000020074


time taken by numpy array :

In [ ]:
np_arr =np.array ([i for i in range(10000)])

start_time=process_time()

np_arr += 5

end_time=process_time()

print(end_time-start_time)

0.001647559999998549


Numpy arrays :    

In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#creating 1 d aarray:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
#creating 2 d array:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a.shape


(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays:


In [ ]:
#create a numpy array of 0's

x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of 1's

y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value

z=np.full((5,4),5)

In [ ]:
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix :

xy=np.eye(4)

In [ ]:
print(xy)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values :

yz=np.random.random((3,4))
print(yz)

[[5.87650773e-01 8.31729838e-01 9.93725545e-01 1.57894184e-01]
 [6.82242834e-01 2.84072191e-01 9.33837558e-01 6.22541897e-01]
 [2.38556296e-04 7.27642173e-01 3.93639263e-01 5.13119592e-01]]


In [ ]:
# create a numpy array with random integers within a specific range:

xz=np.random.randint(10,100,(3,5))
print(xz)


[[23 88 72 58 10]
 [27 28 78 56 84]
 [45 31 85 57 96]]


In [ ]:
# create and array of evenly spaced value -- specifying the no. of values


xyz=np.linspace(10,30,6)

In [ ]:
print(xyz)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced value -- specifying the no. of steps

a=np.arange(10,30,6)
print(a)

[10 16 22 28]


In [ ]:
#convert a list to a numpy array
list2=[10,20,30,40,50]

np_arr=np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 30 40 50]


numpy.ndarray

Analyzing a numpy array

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)


[[52 48 58 10 62]
 [63 45 18 78 35]
 [16 46 88 64 74]
 [42 72 36 39 71]
 [38 59 35 36 54]]


In [ ]:
# array dimension :
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions:
print(c.ndim)

2


In [ ]:
#checking the number of elements in array:
print(c.size)

25


In [ ]:
#checking datatype of elements:
print(c.dtype)

int64


Mathematical operation on a numpy array

In [ ]:
list3=[1,2,3,4,5]
list4=[6,7,8,9,10]

print(list3+list4) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a= np.random.randint(0,10,(3,))
print(a)

[1 6 1]


In [ ]:
b=np.random.randint(0,10,(3,))
print(b)

[7 5 7]


In [ ]:
print(a+b)

[ 8 11  8]


In [ ]:
print(a-b)

[-6  1 -6]


In [ ]:
print(a*b)

[ 7 30  7]


In [ ]:
print(a/b)

[0.14285714 1.2        0.14285714]


In [ ]:
print(np.add(a,b))

[ 8 11  8]


Array manipulation


In [ ]:
array= np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 9 9]
 [3 5 9]]
(2, 3)


In [ ]:
# transpose
trans=np.transpose(array)

In [ ]:
print(trans)

[[9 3]
 [9 5]
 [9 9]]


In [ ]:
print(trans.shape)

(3, 2)


In [ ]:
array= np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 1 5]
 [2 0 7]]
(2, 3)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[3 2]
 [1 0]
 [5 7]]
(3, 2)


In [ ]:
#reshaping array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 5 4]
 [9 1 0]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[9 5]
 [4 9]
 [1 0]]
(3, 2)


In [ ]:
c=b.reshape(1,6)
print(c)

[[9 5 4 9 1 0]]


# New section

Pandas Library :

Useful for Data Processing and Analysis

Pandas DAta Frame:

Pandas Data Frame is a 2 d tabular data structure with labeled axes(rows and colums)

In [ ]:
#importing the pandas library
import pandas as pd