<a href="https://colab.research.google.com/github/div-yash/google-colab-projects/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy : Numerical Python

Advantages:

1. llows several math operations
2. faster operations

In [ ]:
import numpy as np

List vs Numpy - time taken

In [ ]:
from time import process_time

time taken by a list:

In [ ]:
python_list =[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time= process_time()

print(end_time-start_time)



0.0010599680000002998


time taken by numpy array :

In [ ]:
np_arr =np.array ([i for i in range(10000)])

start_time=process_time()

np_arr += 5

end_time=process_time()

print(end_time-start_time)

0.0005067209999998212


Numpy arrays :

In [ ]:
#list
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#creating 1 d aarray:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy arrays:

In [ ]:
#create a numpy array of 0's

x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy array of 1's

y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#array of a particular value

z=np.full((5,4),5)

In [ ]:
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity matrix :

xy=np.eye(4)
print(xy)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values :

yz=np.random.random((3,4))
print(yz)

[[0.86472929 0.64183254 0.77365431 0.42523839]
 [0.63042938 0.8403992  0.94133211 0.06103377]
 [0.912887   0.9521818  0.82531793 0.84975339]]


In [ ]:
# create a numpy array with random integers within a specific range:

xz=np.random.randint(10,100,(3,5))
print(xz)

[[89 51 51 95 86]
 [68 18 33 45 47]
 [15 37 82 74 52]]


In [ ]:
# create and array of evenly spaced value -- specifying the no. of values


xyz=np.linspace(10,30,6)
print(xyz)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced value -- specifying the no. of steps

a=np.arange(10,30,6)
print(a)

[10 16 22 28]


In [ ]:
#convert a list to a numpy array
list2=[10,20,30,40,50]

np_arr=np.asarray(list2)
print(np_arr)
type(np_arr)

[10 20 30 40 50]


numpy.ndarray

Analyzing a numpy array :

In [ ]:
c=np.random.randint(10,90,(5,5))
print(c)

[[42 41 78 31 21]
 [35 19 28 48 35]
 [65 82 38 29 44]
 [68 23 58 50 37]
 [75 47 59 48 87]]


In [ ]:
# array dimension :
print(c.shape)

(5, 5)


In [ ]:
#number of dimensions:
print(c.ndim)

2


In [ ]:
#checking the number of elements in array:
print(c.size)

25


In [ ]:
#checking datatype of elements:
print(c.dtype)

int64


Mathematical operation on a numpy array

In [ ]:
list3=[1,2,3,4,5]
list4=[6,7,8,9,10]

print(list3+list4) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a= np.random.randint(0,10,(3,))
print(a)

[3 2 5]


In [ ]:
b=np.random.randint(0,10,(3,))
print(b)

[4 9 3]


In [ ]:
print(a+b)

[ 7 11  8]


In [ ]:
print(a-b)

[-1 -7  2]


In [ ]:
print(a*b)

[12 18 15]


In [ ]:
print(a/b)

[0.75       0.22222222 1.66666667]


In [ ]:
print(np.add(a,b))

[ 7 11  8]


Array manipulation :

In [ ]:
array= np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 8 4]
 [8 8 5]]
(2, 3)


In [ ]:
# transpose
trans=np.transpose(array)

In [ ]:
print(trans)

[[2 8]
 [8 8]
 [4 5]]


In [ ]:
print(trans.shape)

(3, 2)


In [ ]:
array= np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 8 6]
 [5 5 9]]
(2, 3)


In [ ]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[3 5]
 [8 5]
 [6 9]]
(3, 2)


In [ ]:
#reshaping array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 2 6]
 [9 2 5]]
(2, 3)


In [ ]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[5 2]
 [6 9]
 [2 5]]
(3, 2)


In [ ]:
c=b.reshape(1,6)
print(c)

[[5 2 6 9 2 5]]
